FROM python:3.9

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
RUN python3 -m pip install --upgrade pip
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y
RUN apt install -y libgl1-mesa-glx
RUN apt-get install 'ffmpeg'\
    'libsm6'\
    'libxext6'  -y 

RUN pip3 install opencv-contrib-python==4.10.0.84
RUN pip3 install opencv-python==4.10.0.84
RUN pip3 install tensorflow==2.13.0
RUN pip3 install --no-cache-dir "pandas==2.2.2"
RUN pip3 install deepface==0.0.93
RUN pip3 install ultralytics==8.2.97
RUN pip3 install mediapipe==0.10.15
RUN pip3 install scipy

RUN pip3 install fastapi
RUN pip3 install uvicorn
RUN pip3 install requests
RUN pip3 install python-multipart
RUN pip3 install python-dotenv
RUN pip3 install boto3
RUN pip3 install httpx
RUN pip3 install aioboto3
RUN pip3 install aiobotocore
RUN pip3 install pydantic==2.5.0
RUN pip3 install pydantic-settings

RUN pip3 install Pillow==10.1.0

WORKDIR /app

# Copy requirements first for better caching
# COPY requirements.txt /app/
# RUN pip3 install -r requirements.txt

# Copy source code
COPY main.py /app/
COPY src/ /app/src/
COPY config/ /app/config/
COPY models/ /app/models/
COPY .env /app/

# Create necessary directories
RUN mkdir -p /app/logs /app/static /app/snapshots

# Tải các weights cần thiết
RUN mkdir -p /root/.deepface/weights && \ 
    wget https://github.com/serengil/deepface_models/releases/download/v1.0/vgg_face_weights.h5 -O /root/.deepface/weights/vgg_face_weights.h5 && \
    wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1qcr9DbgsX3ryrz2uU8w4Xm3cOrRywXqb' -O /root/.deepface/weights/yolov8n-face.pt

# EXPOSE 8000

# # Set the command to run the application
# CMD ["python", "main.py"]